# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 11:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_challenge_network_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='feedback',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
